## Python Pandas Tutorials- Part 1

In Part we are going to learn about

1.Pandas Dataframe

2.Pandas Series

3.Pandas Basic Operations

In [1]:
#pandas dataframe

In [2]:
import pandas as pd
import numpy as np

In [3]:
arr=np.arange(0,20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
df=pd.DataFrame(arr,index=['Row1','Row2','Row3','Row4','Row5'],columns=['Col1','Col2','Col3','Col4'])
df

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [5]:
df.head()

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [6]:
df.tail()

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    5 non-null      int64
 1   Col2    5 non-null      int64
 2   Col3    5 non-null      int64
 3   Col4    5 non-null      int64
dtypes: int64(4)
memory usage: 200.0+ bytes


In [9]:
df.describe()

Col1       Col2       Col3       Col4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [10]:
## indexing

In [11]:
df

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [12]:
type(df['Col1'])

pandas.core.series.Series

In [13]:
df[['Col1','Col2','Col3','Col4']]

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [14]:
# using row index name loc

In [15]:
df.loc[['Row3','Row4']]

Col1  Col2  Col3  Col4
Row3     8     9    10    11
Row4    12    13    14    15

In [16]:
df.head()

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [17]:
df.iloc[2:4,:2]

Col1  Col2
Row3     8     9
Row4    12    13

In [18]:
df.iloc[2:5,1:]

Col2  Col3  Col4
Row3     9    10    11
Row4    13    14    15
Row5    17    18    19

In [19]:
df.iloc[3:4,1:2]

Col2
Row4    13

In [20]:
#converting Dataframe into arrays
df

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [21]:
df.iloc[:,:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [22]:
##Basic operation
df.isnull().sum()

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64

In [23]:
df1=pd.DataFrame(data=[[1,np.nan,2], [3,4,6]], index = ['Row1','Row2'], columns=['Col1','Col2','Col3'])
df

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [24]:
df1.isnull().sum()

Col1    0
Col2    1
Col3    0
dtype: int64

In [25]:
df1.isnull().sum()==0

Col1     True
Col2    False
Col3     True
dtype: bool

In [26]:
df1['Col3'].value_counts()

Col3
2    1
6    1
Name: count, dtype: int64

In [27]:
df

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [30]:
df['Col2'].unique()

array([ 1,  5,  9, 13, 17])

In [34]:
df[df['Col2']>9]

Col1  Col2  Col3  Col4
Row4    12    13    14    15
Row5    16    17    18    19